name: pre-commit autoupdate

on:
  pull_request:
    paths:
      - .pre-commit-config.yaml

jobs:
  copy:
    name: Copy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: Copy
        run: cp --target-directory='template' --verbose '.pre-commit-config.yaml'
      - name: Commit
        uses: liblaf/actions/commit@dist
        with:
          message: ${{ github.event.pull_request.title }}

  approve:
    name: Approve
    needs:
      - copy
    if: github.event.pull_request.user.login == 'pre-commit-ci[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        uses: liblaf/actions/approve@dist
        with:
          authors: pre-commit-ci[bot]
          bot: true
          pull-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GH_PAT }}

  auto-merge:
    name: Auto Merge
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'pre-commit-ci[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Add Label
        run: gh pr edit '${{ github.event.pull_request.html_url }}' --add-label 'automerge'
        env:
          GH_TOKEN: ${{ github.token }}
